# Generated by Django 4.1.7 on 2023-06-13 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='following',
            field=models.ManyToManyField(related_name='posts_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
