# Generated by Django 4.1.7 on 2023-06-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_following_post_user_alter_post_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='following',
        ),
    ]
