# Generated by Django 4.1.7 on 2023-06-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_follow_trigger_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='trigger_text',
            field=models.CharField(choices=[('F', 'Follow'), ('U', 'UnFollow')], default='F', max_length=1),
        ),
    ]
