# Generated by Django 4.1.7 on 2023-06-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_follow_trigger_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
