# Generated by Django 4.1.7 on 2023-06-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
