# Generated by Django 4.1.7 on 2023-06-27 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_post_likenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='network.post')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_liked_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
