# Generated by Django 4.1.7 on 2023-06-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_like_owner_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_status',
            field=models.CharField(default='liked', max_length=10),
        ),
    ]
