# Generated by Django 4.1.7 on 2023-06-28 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_like_like_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likeNum',
        ),
        migrations.AddField(
            model_name='post',
            name='likePeople',
            field=models.ManyToManyField(blank=True, related_name='who_clicked_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
